### ISSUE TITLE
Deploy to Azure fail

### ISSUE THREAD

**Issue by almostsultry** [heyAyushh/qrfn#1]
The Deploy to Azure button in readme.md is not working.

**Comment by heyAyushh** [comment]
Fixed! closing for the time being, if you find the same bug again, reopen the issue

**Comment by almostsultry** [comment]
I hate to do this, but I tried this again today and got the attached error:

![image](https://user-images.githubusercontent.com/4964731/135341225-01d42fdc-16e3-454c-bcd7-697434e7a54e.png)
